### ISSUE TITLE
Implement native session support

### ISSUE THREAD

**Issue by davidchappelle** [tavendo/AutobahnCpp#57]
I am looking at how I can integrate native support into AutobahnCpp. The main driver here is to integrate with Bonefish which is the C++ WAMP Router implementation. I was initially building on top of PR #56 and trying to implement a *wamp_native_transport*. I am starting to feel that this is not the correct approach as the message passing back and forth between the router and the component doesn't quite work within the API *write* and *async_read*. I am going to continue trying to find an elegant way to make things work using the existing *wamp_session* and deriving a *wamp_native_transport* however, I am opening this issue to gather some feedback from others in the community. Perhaps the best approach would be to implement a *wamp_native_session* rather than trying to reuse *wamp_session*? Thoughts?

**Comment by davidchappelle** [comment]
I think I have this working now.

**Comment by jpetso** [comment]
Note that an external dependency is only a dependency if the code is built. Since AutobahnCpp is a header-only library, it should be possible to merely provide an additional header file and anyone who wants to accept this dependency can include that additional header file. Assuming that AutobahnCpp offers abstract interfaces for transports/messages. Depending on what code it's most coupled to (I guess), that header could go into either AutobahnCpp or Bonefish.
